name: 'Pulumi-Action'
description: 'Deploy apps and infra to a favorite cloud (forked from `amichel/pulumi-github-action` who forked from `pulumi/action`)'
branding:
  color: yellow
  icon: cloud-lightning
runs:
  using: 'node12'
  main: 'index.js'
inputs: {}
outputs: {}
author: 'Yellow Brim'
