name: 'Pulumi-Action'
description: 'Deploy apps and infra to a favorite cloud (forked from `amichel/pulumi-github-action` who forked from `pulumi/action`)'
branding:
  color: yellow
  icon: cloud-lightning
runs:
  using: 'node12'
  main: 'index.js'
inputs:
  value:
    required: true
    description: 'The `value` will be assigned to the contents of the matching `yq-path`'
  yq-path:
    required: true
    description: 'The key to update (example: `config.osys:onboarding-image`)'
  yml-file:
    default: Pulumi.dev.yaml
    required: false
    description: Which Pulumi config file to update
  yml-file-encoding:
    default: utf8
    required: false
    description: Used in advanced usecases in fs.readFileSync
outputs: {}
author: 'Yellow Brim'
